#!/bin/bash

set -eu
set -x

#ocamlc \
#    -I +camlp4 \
#    -pp camlp4oof \
#    minml.ml \
#    -o minml \
#    $(ocamlfind -query llvm)/llvm.cma

ocamlc \
  -I ~/.opam/4.02.2/lib/llvm llvm.cma \
  -I ~/.opam/4.02.2/lib/ocaml dynlink.cma \
  -I ~/.opam/4.02.2/lib/ocaml/camlp4 camlp4lib.cma \
  -I +camlp4 \
  -pp camlp4oof \
  minml.ml \
  -o minml
  -cclib -lstdlib++ \
  -xc++

#  -cc clang++ \
