#!/bin/bash

ocamlopt -I +llvm llvm.cmxa hello.ml -o hello
exit 0

ocamlopt -cc g++ llvm.cmxa llvm_bitwriter.cmxa -o metahelloworld metahelloworld.ml
./metahelloworld helloworld.bc
llvm-dis < helloworld.bc
llc -o helloworld.s helloworld.bc
gcc -o helloworld helloworld.s
./helloworld
