all: \
	AdderChannel \
	AdderMismatch \
	AdderBlocking \
	AdderService \
	Processes \
	Process \
	ProcessState \
	ProcessGeneric

AdderChannel: AdderChannel.idr
	idris -o $@ $<

AdderMismatch: AdderMismatch.idr
	idris -o $@ $<

AdderBlocking: AdderBlocking.idr
	idris -o $@ $<

AdderService: AdderService.idr
	idris -o $@ $<

Processes: Processes.idr
	idris -o $@ $<

Process: Process.idr
	idris -o $@ $<

ProcessState: ProcessState.idr
	idris -o $@ $<

ProcessGeneric: ProcessGeneric.idr
	idris -o $@ $<
